import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://orqawebms.parafait2.com/login');
    await page.getByRole('textbox', { name: 'Enter Login ID' }).click();
    await page.getByRole('textbox', { name: 'Enter Login ID' }).fill('semnox');
    await page.getByRole('textbox', { name: 'Enter Password' }).click();
    await page.getByRole('textbox', { name: 'Enter Password' }).fill('semnoX!1');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.getByText('Select SiteSelect Site').click();
    await page.getByText('ORQASITEA').click();
    await page.locator('a').filter({ hasText: 'Site Setup' }).click();
    await page.getByRole('link', { name: 'Custom Attributes' }).click();
    await page.getByRole('button', { name: '+' }).click();
    await page.getByRole('textbox', { name: 'Attribute Name' }).fill('p1');
    await page.locator('#mat-select-value-7').click();
    await page.locator('#mat-option-10').getByText('TEXT').click();
    await page.locator('#mat-select-value-9').click();
    await page.getByText('CUSTOMER').click();
    await page.getByRole('button', { name: 'Save save' }).click();
    await page.getByText('Record has been saved successfullyClose').click();
    await page.getByText('Record has been saved').click();
    await page.getByRole('button', { name: 'Close' }).click();
    await page.getByText('X', { exact: true }).click();
    await page.getByRole('button', { name: '+' }).click();
    await page.getByRole('textbox', { name: 'Attribute Name' }).fill('list1');
    await page.locator('#mat-select-value-11').click();
    await page.locator('#mat-option-29').getByText('LIST').click();
    await page.locator('#mat-select-value-13').click();
    await page.locator('#mat-option-33').getByText('PRODUCT').click();
    await page.getByRole('button', { name: 'Save save' }).click();
    await page.getByText('Record has been saved').click();
    await page.getByText('Record has been saved').click();
    await page.getByText('X', { exact: true }).click();
    await page.locator('#mat-input-1').click();
    await page.locator('#mat-input-1').fill('list1');
    await page.locator('#mat-checkbox-10 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
    await page.locator('app-attribute-values').getByRole('button', { name: '+' }).click();
    await page.getByRole('textbox', { name: 'Value' }).fill('l11');
    await page.getByRole('button', { name: 'Save save' }).click();
    await page.getByText('Record has been saved').click();
    await page.getByText('X', { exact: true }).click();
});